# Icon Blacklist.
icon-blacklist:
  - ':middle_finger_light_skin_tone:'
  - ':middle_finger_medium_light_skin_tone:'
  - ':middle_finger_medium_dark_skin_tone:'
  - ':middle_finger_dark_skin_tone:'
  - ':middle_finger:'
  - ':middle_finger_medium_skin_tone:'
  - ':mouth:'
  - ':tongue:'
  - ':bikini:'
  - ':kiss:'
  - ':sweat_droplets:'
  - ':banana:'
  - ':cherries:'
  - ':peach:'
  - ':tomato:'
  - ':eggplant:'
  - ':cucumber:'
  - ':beer_mug:'
  - ':clinking_beer_mugs:'
  - ':clinking_glasses:'
  - ':wine_glass:'
  - ':tumbler_glass:'
  - ':cocktail_glass:'
  - ':face_with_symbols_on_mouth:'
  - ':face_vomiting:'
  - ':a:'
  - ':b:'
  - ':c:'
  - ':d:'
  - ':e:'
  - ':f:'
  - ':g:'
  - ':h:'
  - ':i:'
  - ':j:'
  - ':k:'
  - ':l:'
  - ':m:'
  - ':n:'
  - ':o:'
  - ':p:'
  - ':q:'
  - ':r:'
  - ':s:'
  - ':t:'
  - ':u:'
  - ':v:'
  - ':w:'
  - ':x:'
  - ':y:'
  - ':z:'
  - ':1:'
  - ':2:'
  - ':3:'
  - ':4:'
  - ':5:'
  - ':6:'
  - ':7:'
  - ':8:'
  - ':9:'
  - ':0:'